# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3.8'

services:
  dockovpn:
    hostname: dockovpn
    container_name: dockovpn
    build: .
    cap_add:
        - NET_ADMIN
    ports:
        - 1194:1194/udp
    environment:
        HOST_ADDR: ${HOST_ADDR} 
    volumes:
        - dockovpn_data:/opt/Dockovpn_data
        - ./openvpn_conf/clients:/opt/Dockovpn_data/clients
        - ./openvpn_conf/ccd:/etc/openvpn/ccd   
    restart: always
    networks:
        - eth

volumes:
    dockovpn_data:

networks:
    eth:
