port 1194
proto %HOST_TUN_PROTOCOL%
dev tun

ca /etc/openvpn/ca.crt
cert /etc/openvpn/MyReq.crt
key /etc/openvpn/MyReq.key
dh /etc/openvpn/dh.pem
server 10.9.12.0 255.255.255.0
#push "route 10.9.12.0 255.255.255.0"

ifconfig-pool-persist ipp.txt
#push "redirect-gateway def1 bypass-dhcp"
#push "dhcp-option DNS 208.67.222.222"
#push "dhcp-option DNS 208.67.220.220"
duplicate-cn # Potenzialmente pericoloso, ma necessario se si vogliono più client con lo stesso certificato
keepalive 10 120

data-ciphers AES-128-GCM:AES-256-GCM
data-ciphers-fallback AES-128-GCM
#cipher AES-256-GCM
#ncp-ciphers AES-256-GCM:AES-256-CBC
auth SHA256

persist-key
persist-tun

status openvpn-status.log
verb 1

tls-server
tls-version-min 1.2
tls-auth /etc/openvpn/ta.key 0

crl-verify /etc/openvpn/crl.pem

client-to-client
client-config-dir /etc/openvpn/ccd

sndbuf 0
rcvbuf 0
push "sndbuf 0"
push "rcvbuf 0"

tun-mtu 1500
mssfix 1400
#fragment 0 # Errore valore inferiore a 68 byte